# Generated by Django 4.2.7 on 2025-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_name', models.CharField(max_length=300)),
                ('product_name_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(default='قطعة', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_stock_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_decimal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'fox_system"."products',
                'managed': False,
            },
        ),
    ]
