# Generated by Django 4.2.7 on 2025-12-04 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_by_method', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'db_table': 'fox_system"."shifts',
                'ordering': ['-start_time'],
            },
        ),
    ]
