# Generated by Django 4.2.7 on 2025-12-04 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('بيع', 'بيع'), ('شراء', 'شراء'), ('مصروف', 'مصروف'), ('مرتجع', 'مرتجع'), ('تسوية مخزون', 'تسوية مخزون'), ('إيداع رأس مال', 'إيداع رأس مال'), ('مسحوبات شخصية', 'مسحوبات شخصية'), ('تسوية دين', 'تسوية دين')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('كاش', 'كاش'), ('محفظة', 'محفظة'), ('Instapay', 'Instapay'), ('آجل', 'آجل')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='completed', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_direct_sale', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_customer', models.ForeignKey(blank=True, db_column='related_customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('related_supplier', models.ForeignKey(blank=True, db_column='related_supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
                ('shift', models.ForeignKey(blank=True, db_column='shift_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.shift')),
            ],
            options={
                'verbose_name': 'معاملة',
                'verbose_name_plural': 'المعاملات',
                'db_table': 'fox_system"."transactions',
                'ordering': ['-date'],
            },
        ),
    ]
