# Generated by Django 4.2.7 on 2025-12-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('settings_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='FOX GROUP', max_length=200)),
                ('company_phone', models.CharField(default='', max_length=20)),
                ('company_address', models.TextField(default='')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('auto_print', models.BooleanField(default=False)),
                ('next_invoice_number', models.IntegerField(default=1001)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5)),
                ('prevent_negative_stock', models.BooleanField(default=False)),
                ('invoice_terms', models.TextField(default='')),
                ('current_shift', models.ForeignKey(blank=True, db_column='current_shift_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_settings', to='api.shift')),
            ],
            options={
                'verbose_name': 'إعدادات التطبيق',
                'verbose_name_plural': 'إعدادات التطبيق',
                'db_table': 'fox_system"."app_settings',
            },
        ),
    ]
