# Generated by Django 4.2.7 on 2025-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('invoice_date', models.DateField(primary_key=True, serialize=False)),
                ('total_invoices', models.IntegerField()),
                ('unique_customers', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_invoices', models.IntegerField()),
                ('partial_invoices', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ملخص المبيعات اليومي',
                'verbose_name_plural': 'ملخص المبيعات اليومي',
                'db_table': 'fox_system"."v_daily_sales_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_value_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_value_selling', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_stock_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'تقرير المخزون',
                'verbose_name_plural': 'تقارير المخزون',
                'db_table': 'fox_system"."v_inventory_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutstandingDebt',
            fields=[
                ('debt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('debt_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=200)),
                ('entity_phone', models.CharField(max_length=50)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('aging_status', models.CharField(max_length=50)),
                ('days_overdue', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'تقرير الديون',
                'verbose_name_plural': 'تقارير الديون',
                'db_table': 'fox_system"."v_outstanding_debts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityReport',
            fields=[
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'تقرير الربحية',
                'verbose_name_plural': 'تقارير الربحية',
                'db_table': 'fox_system"."v_profitability_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreasuryBalanceReport',
            fields=[
                ('payment_method', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'تقرير الخزينة',
                'verbose_name_plural': 'تقارير الخزينة',
                'db_table': 'fox_system"."v_treasury_balance',
                'managed': False,
            },
        ),
    ]
